version: 'v1'
kind: 'PHPAConfig'
verbose: 'true'
dryRun: 'true'
# cool down time(in seconds) after performing an action
actionCooldown: '300'
# info used to manipulate the k8s object/deployments
deployment:
  name: 'backend-staging-deployment'
  namespace: 'default'
  minReplicas: '1'
  maxReplicas: '4'
  fallbackReplicas: '2'
metric:
  # name of metric, used to know what these configs are
  name: 'server_capacity'
  # positive means if metrics value is great then threshold then it's good and
  # we should scale down
  # negative means if metrics value is great then threshold then it's bad and we should
  # scale up
  # if metric value falls under metricThreshold +/- metricMargin the do nothing
  metricType: 'negative'
  metricThreshold: '32'
  metricMargin: '16'
# used to select and get metrics from metric_server
metricServer:
  adaptor: 'influxdb'
  influxdb:
    host: 'metric-server' # 10.132.0.59
    port: '8086'
    username: 'admin'
    password: 'admin'
    database: 'server_stats'
    query: "SELECT mean(\"pool_capacity\") FROM \"puma\" WHERE (\"env\" = 'production') AND time >= now() - 10m GROUP BY time(1m)"
  graphite:
    host: 'graphite-server' # 10.132.0.5
    port: '8013'
    query: "target=summarize(production.kafka-lag.kafka-cluster-1.topics.*.production_*.lag, '1min', 'avg', false)&from=-10min&until=now&format=json"
