# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: final_newline, final_blank_line
Layout/TrailingEmptyLines:
  Exclude:
    - 'lib/errors.rb'
    - 'lib/helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 5
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/errors.rb'
    - 'lib/helper.rb'
    - 'spec/decision_spec.rb'
    - 'spec/errors_spec.rb'
    - 'spec/spec_helper.rb'

# Offense count: 106
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'lib/cli.rb'
    - 'lib/config.rb'
    - 'lib/graphite.rb'
    - 'lib/helper.rb'
    - 'lib/influx.rb'
    - 'lib/kubernetes_runner.rb'
    - 'phpa-cli'
    - 'spec/decision_spec.rb'
    - 'spec/errors_spec.rb'
    - 'spec/spec_helper.rb'
