apiVersion: batch/v1beta1
kind: CronJob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: phpa-service-account
          containers:
          - name: phpa
            image: <docker registry>/phpa:latest
            imagePullPolicy: Always
            args:
            - ./phpa-cli -f support/sample_config.yml
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
          restartPolicy: Never